### ISSUE TITLE
No mixin refMap specified, causing startup crash

### ISSUE THREAD

**Issue by input-Here** [N4TH4NOT/Dynamic-FPS-Reforged#1]
The game currently crashes on startup due to a failed mixin apply. There’s a fork by Kasualix with a [commit](https://github.com/Kasualix/Dynamic-FPS-Reforged/commit/22cabb1f68285247a2f7638e99f3f9ae804b7b08) that fixes this issue and seems to work fine from some brief testing (using a compiled fork of 1.1 with this commit merged). 
I don't know what the norm is for merging stuff from forks, but I doubt you'd need permission for this because I'd imagine there's only so many ways to fix this? 

debug.log message of crash cause:
> [18Jan2024 16:23:02.735] [main/FATAL] [mixin/]: Mixin apply failed dynamicfps.mixins.json:GameRendererMixin -> net.minecraft.client.renderer.GameRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onRender could not find any targets matching 'render' in net.minecraft.client.renderer.GameRenderer. No refMap loaded. [PREINJECT Applicator Phase -> dynamicfps.mixins.json:GameRendererMixin -> Prepare Injections ->  -> handler$zdl000$onRender(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]

Relevant logs:
* [debug.log](https://github.com/N4TH4NOT/Dynamic-FPS-Reforged/files/13979827/debug.log)
* [latest.log](https://github.com/N4TH4NOT/Dynamic-FPS-Reforged/files/13979828/latest.log)
* (It does not produce a crash report)

**Comment by input-Here** [comment]
Upstream now has an official forge port for 1.16.5

**Comment by N4TH4NOT** [comment]
Sorry for the delay, I never noticed the notification.
I have taken note of your message and I will update the mod accordingly.
Thank you very much for your feedback and your participation.

**Comment by input-Here** [comment]
Hi, no worries about the delay, but I closed this issue because this port is redundant as upstream DynamicFPS supports Forge 1.16.5 now. 
I'll leave this issue open in case you still want to fix this, I just don't think it's worthwhile anymore. Either way, thanks for your original efforts porting the mod :)
