### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ArbysAmerica** [N4TH4NOT/Dynamic-FPS-Reforged#2]
game crashes when i use the mod. Probably a conflict between mods or smth, not too sure.
[crash-2024-03-10_19.04.40-client.txt](https://github.com/N4TH4NOT/Dynamic-FPS-Reforged/files/14551071/crash-2024-03-10_19.04.40-client.txt)

**Comment by ArbysAmerica** [comment]
[latest.log](https://github.com/N4TH4NOT/Dynamic-FPS-Reforged/files/14551088/latest.log)
accidentaly sent the one with some other mods that werent present beforehand

**Comment by LostLuma** [comment]
Hi, I'm not sure if you're still looking for a solution but upstream Dynamic FPS now supports Forge and NeoForge, which may or may not solve this issue for you.

**Comment by N4TH4NOT** [comment]
Sorry for the delay, I never noticed the notification.
I have looked in detail at the origin of your problem and I think I have found a solution if it is indeed my implementation which is at the origin of the problem.

I will update to the latest version of the original mod and hope that fixes your problem.

I keep you informed.

**Comment by LostLuma** [comment]
@N4TH4NOT what's the point in updating your fork now when the original mod has Forge support ..? We support all versions above 1.16.5 as well.

**Comment by N4TH4NOT** [comment]
I didn't know anything about it, it had been a long time since I looked at the progress.
